Hotel7Star/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView
from decouple import config
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static


# naming the system
admin.site.site_header = config('ADMIN_APP_SITE_HEADER')
admin.site.index_title = config('APP_NAME')
admin.site.site_title = config('ADMIN_APP_SITE_TITLE')

urlpatterns = [
    path('admin/', admin.site.urls),

    # frontedn routes
    path('', include('apps.frontend.hotel.urls')),

    # backend routes
    path('system/', login_required(TemplateView.as_view(template_name='backend/home/index.html')), name='system'),

    path('system/', include('apps.backend.users.urls')),
    

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/frontend/hotel/urls.py
from django.urls import path
from . import views
from .views import *

from django.views.generic import TemplateView, RedirectView

app_name = 'hotel'
urlpatterns = [
    path('', TemplateView.as_view(template_name='frontend/index.html'), name='home'),
    path('contact-us/', EnquiryView.as_view(), name='contact-us'),
    path('about-us/', TemplateView.as_view(template_name='frontend/about-us.html'), name='about-us'),
    path('gallery1/', TemplateView.as_view(template_name='frontend/gallery1.html'), name='gallery1'),
    path('gallery2/', TemplateView.as_view(template_name='frontend/gallery2.html'), name='gallery2'),
    path('login/',StaffLoginField.as_view() , name='login'),
    path('room/', TemplateView.as_view(template_name='frontend/room.html'), name='room'),
    path('room-list/', TemplateView.as_view(template_name='frontend/room-list.html'), name='room-list'),
    path('room-detail/', TemplateView.as_view(template_name='frontend/room-detail.html'), name='room-detail'),
    # path('signup/', TemplateView.as_view(template_name='frontend/signup.html'), name='signup'),
    # path('register', views.userRegister, name='userReg'),
    # path('logout/', staffLogout.as_view(),name='logout'),
    path('signup/',staffField.as_view(),name="signup"),
    path('logout/',StaffLogoutField.as_view(),name="logout"),
    path('staff/', TemplateView.as_view(template_name='frontend/staff.html'), name='staff'),
    path('addevent/',Eventsview.as_view(),name='addevent'),
    path('events/',Eventdisplay,name='events'),
    path('blog/', Blogdisplay,name='blog'),
    path('addblog/', Blogview.as_view(), name='addblog')
    
]

apps/frontend/hotel/models.py
from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
# Create your models here.

class Staff(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    password = models.CharField(max_length=50)
    email = models.TextField()    
    phone_number = models.CharField(max_length=10)

    def __str__(self):
        return self.first_name
    

        

apps/frontend/hotel/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.db.models import fields
from .models import Staff
from django import forms

class StaffRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput())
    class Meta:
        model = Staff 
        fields = ['first_name','last_name','email','phone_number','password']

apps/frontend/hotel/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models.fields import CommaSeparatedIntegerField
from django.http.response import HttpResponse
from django.shortcuts import redirect,render
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.base import View
from django.views.generic.edit import CreateView
from apps.backend.users.forms import BlogForm, EventsForm, UserRegistrationForm, EnquiryForm
from apps.backend.users.models import Blog, Enquiry,Events
from django.contrib import messages
from django.urls import reverse_lazy
from  apps.backend.users.models import User
from django.views.generic.edit import FormView

# Create your views here.

# def userRegister(request):
#     print('hello',request.method)
#     if request.method == "POST":
#         fname = request.POST['fname']
#         lname = request.POST['lname']
#         email = request.POST['email']
#         password = request.POST['password']
#         cpassword = request.POST['cpassword']
#         mobile = request.POST['mobile']
#         user = userReg.objects.filter(Email=email) 
#         if user:
#             message="User already exist"
#             print(message)
#             return render(request,"frontend/signup.html", {'msg':message}) 
#         else:
#             if password==cpassword:
#                 newuser = userReg.objects.create(Firstname=fname,Lastname=lname,Password=password,Email=email,Mobile=mobile)
#                 message="registration sucessfull"
#                 newuser.save()
#                 print(message)
#                 return redirect(reverse_lazy("hotel:userReg"))
#                 # return render(request,"frontend/index.html",{'msg':message})    
#             else:
#                 message="password doesn't match"
#                 print(message)
#                 return render(request,"frontend/signup.html", {'msg':message})

#     else:
#         return HttpResponse("none")      

      
class staffField(SuccessMessageMixin, CreateView):
        template_name='frontend/signup.html'
     
        form_class = UserRegistrationForm
        success_message = 'User Successfully Created'
        success_url = reverse_lazy('hotel:home')
       

        def form_valid(self, form):
            user = form.save(commit=False)
            user.is_buyer = True           
            user.save()
            messages.success(self.request, self.success_message)
            return redirect(self.success_url)

class StaffLogoutField(LogoutView):
    template_name = 'frontend/home.html'



class StaffLoginField(LoginView):
    template_name = 'frontend/login.html'  

    def get_success_url(self):
        return redirect(reverse_lazy('hotel:home'))

    # return super().get_success_url()

class ContactUsField(SuccessMessageMixin, CreateView):
    template_name = 'frontend/contact-us.html'



class EnquiryView(FormView):
   
    template_name = 'frontend/contact-us.html'
    form_class = EnquiryForm
    # print("1")

    def form_valid(self, form):
        contact = form.save(commit=False)
        contact.save()   
        print("2")
        return redirect(reverse_lazy('hotel:home')) 

class Eventsview(FormView):

    template_name = 'frontend/addevent.html'
    form_class = EventsForm
    
    def form_valid(self,form):
        event = form.save(commit=False)
        event.save()

        return redirect(reverse_lazy('hotel:events'))

def Eventdisplay(request):
    data = Events.objects.all()

    return render(request,'frontend/events.html',{'data':data})

class Blogview(FormView):

    template_name = 'frontend/addblog.html'
    form_class = BlogForm

    def form_valid(self,form):
        blog = form.save(commit= False)
        blog.image = form.cleaned_data['image']
        blog.save()

        return redirect(reverse_lazy('hotel:blog'))

def Blogdisplay(request):

    data = Blog.objects.all()

    return render(request,'frontend/blog.html',{'data':data})        




    
    

templates/frontend/layouts/footer.html
<footer class="hotel-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-6">
                <!--About Widget Start-->
                <div class="widget about-widget widget-info2">
                    <h4 class="widget-title"><span>About Us</span></h4>
                    <div class="text">
                        <p>Lorem Ipsum is simply dummy text of the printing iste and is the best inisistin typesetting
                            industry. theisstandar dis dummy text ever sinc...</p>
                        <!--About Text Thumb Start-->
                        <div class="about-text">
                            <span class="th-bg"><i class="fa fa-phone"></i></span>
                            <div class="overflow-text">
                                <address>1234 Fleming Road Manhatten 2 cross Newyork US</address>
                            </div>
                        </div>
                        <!--About Text Thumb End-->
                        <!--About Text Thumb Start-->
                        <div class="about-text">
                            <span class="th-bg"><i class="fa fa-phone"></i></span>
                            <div class="overflow-text">
                                <a href="#">+92 - 33267 -124589</a>
                                <a href="#">+92 - 33267 -124589</a>
                            </div>
                        </div>
                        <!--About Text Thumb End-->
                        <!--About Text Thumb Start-->
                        <div class="about-text">
                            <span class="th-bg"><i class="fa fa-envelope"></i></span>
                            <div class="overflow-text">
                                <a href="#">oscarthemes@gmail.com</a>
                                <a href="#">oscarthemes@gmail.com</a>
                            </div>
                        </div>
                        <!--About Text Thumb End-->
                    </div>
                </div>
                <!--About Widget End-->
            </div>
            <div class="col-md-4 col-sm-6">
                <!--Flickr Widget Start-->
                <div class="widget flicker-widget">
                    <h4 class="widget-title"><span>Flickr Feed</span></h4>
                    <div>
                        <ul id="flickr-feeds" class="popup-gallery"></ul>
                    </div>
                </div>
                <!--Flickr Widget End-->
            </div>
            <div class="col-md-4 col-sm-12">
                <!--Twitter Widget Start-->
                <div class="widget twitter-widget">
                    <h4 class="widget-title"><span>Latest Twitter</span></h4>
                    <div id="twitter-feeds"></div>
                </div>
                <!--Twitter Widget End-->
            </div>
        </div>
    </div>
</footer>

templates/frontend/layouts/header.html
{% load static %}


<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="robots" content="index, follow">
<meta name="keywords"
      content="HTML5 Template, Hotels near me, Motel, booking hotel,hotel booking,rooms,discounted,offers,deals,last minute,hotels,oscarthemes,Oscar Themes,Jasmine Hotel">
<meta name="description"
      content="Discover Oscar Themes - Jasmine Hotel HTML5 Template, Hotel, Travel,Top Destinations Discover responsive Bootstrap templates, & HTML templates,">
<meta name="theme-color" content="#f4b843">
<title>Home Hotel</title>
<!-- Css Plugin Css Collection -->
<link href="{% static 'frontend/css/css-plugin-collection.css' %}" rel="stylesheet">
<!-- Theme Default Css -->
<link href="{% static 'frontend/css/typography.css' %}" rel="stylesheet">
<!-- Short Codes Css -->
<link href="{% static 'frontend/css/shortcodes.css' %}" rel="stylesheet">
<!-- Style Css -->
<link href="{% static 'frontend/style.css' %}" rel="stylesheet">
<!-- Color Css -->
<link href="{% static 'frontend/css/color.css' %}" rel="stylesheet">
<!-- Responsive Css -->
<link href="{% static 'frontend/css/responsive.css' %}" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i&display=swap" rel="stylesheet">
        
        <!-- <link rel="stylesheet" href="{% static 'frontend/css/owl.carousel.min.css' %}"> -->
<!-- <link rel="stylesheet" href="{% static 'frontend/css/owl.theme.default.min.css' %}"> -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/4.5.6/css/ionicons.min.css">
        <!-- <link rel="stylesheet" href="{% static 'frontend/css/animate.css' %}"> -->
        <!-- <link rel="stylesheet" href="{% static 'frontend/css/eventstyle.css' %}"> -->


<!-- FAVICONS -->
<link rel="shortcut icon" href="{% static 'frontend/images/favicon/favicon.png' %}">
<link rel="apple-touch-icon" href="{% static 'frontend/images/favicon/apple-touch-icon.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'frontend/images/favicon/apple-touch-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'frontend/images/favicon/apple-touch-icon-114x114.png' %}">



<link rel="icon" sizes="192x192" href="{% static 'frontend/images/favicon/icon-192x192.png' %}">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

templates/frontend/layouts/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'frontend/layouts/header.html' %}
</head>
<body>
<!-- LOADER -->
<div id="loader-overflow">
    <div id="loader3" class="loader-cont">Please enable JS</div>
</div>
<div class="chr-wrapper">
    <!-- Header Hotel Start -->
    {% include 'frontend/layouts/navheader.html' %}
    <!-- Header Hotel End -->
    <!--Banner Wrap Start-->
    {% include 'frontend/layouts/sidebar.html' %}
    <!--Banner Wrap End-->
    {% block content %}

    {% endblock %}
    <!--News Letter Wrap Start-->
    {% include 'frontend/layouts/newsletter.html' %}
    <!--News Letter Wrap End-->
    <!--Hotel Footer Start-->
    {% include 'frontend/layouts/footer.html' %}
    <!--Hotel Footer End-->
    <div class="osr-copyright th-bg">
        <p>Copyrights 2016-17. All rights reserved by:<a target="_blank" href="http://themeforest.net/user/oscarthemes">
            OSCAR THEMES</a></p>
    </div>
</div>
{% include 'frontend/layouts/script.html' %}
</body>
</html>

templates/frontend/layouts/message.html
<script>
    {% if messages %}
        {% for message in messages %}
            const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 5000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            })

            Toast.fire({
                icon: 'success',
                title: '{{ message }}'
            })

        {% endfor %}

    {% endif %}
</script>

templates/frontend/layouts/navheader.html
{% load static %}


<header id="nav" class="sticky-header header-1">
    <!-- Top Bar Start -->
    <div class="chr-top-bar">
        <div class="pull-left">
            <div class="chr-top-info"><i class="fa fa-phone"></i><span>+977- 986922222</span></div>
            <div class="chr-top-info email-info"><i class="fa fa-envelope"></i><span>statesevenhotel@gmail.com</span></div>
        </div>
        <div class="pull-right">
            <ul class="chr-social rd-0">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-tripadvisor"></i></a></li>
            </ul>
            <a class="chr-top-info chr-admin" href="{% url 'hotel:signup' %}">
                <i class="fa fa-user"></i>
                <span>Signup</span>
                
                {% if user.is_authenticated %}

                {% csrf_token %}
                <form action="/logout">
                <input type="submit" value="logout" />
                </form>
                 {% endif %}
            </a>
        </div>
    </div>
    <!-- Top Bar Start -->
    <!-- Top Bar Start -->
    <div class="chr-logo-outer">
        <div class="container">
            <div class="navigation-outer">
                <nav class="navigation pull-left">
                    <ul>
                        <li class="active"><a href="{% url 'hotel:home' %}">Home</a></li>
                        <li><a href="{% url 'hotel:about-us' %}">About Us</a></li>
                        <li><a href="#">Rooms</a>
                            <ul class="children">
                                <li><a href="{% url 'hotel:room' %}">Our Rooms</a></li>
                                <li><a href="{% url 'hotel:room-list' %}">Room List</a></li>
                                <li><a href="{% url 'hotel:room-detail' %}">Room Detail</a></li>
                            </ul>
                        </li>
                        <li><a href="{% url 'hotel:events' %}">Event</a>
{#                            <ul class="children">#}
{#                                <li><a href="event-small.html">Event Small</a></li>#}
{#                                <li><a href="event-medium.html">Event Medium</a></li>#}
{#                                <li><a href="event-large.html">Event Large</a></li>#}
{#                                <li><a href="event-list.html">Event List</a></li>#}
{#                                <li><a href="event-detail.html">Event Detail</a></li>#}
{#                            </ul>#}
                        </li>
                    </ul>
                </nav>
                <h1 class="logo">
{#                    <a href="#"><img src="{% static 'images/hotel-logo.png' %}" alt="Oscar Themes"/></a>#}
                    <a href="#"><img src="{% static 'frontend/images/hotel-7-logo.png' %}" width="1200" alt="Oscar Themes"/></a>
                </h1>
                <nav class="navigation pull-right">
                    <ul>
                        <li><a href="{% url 'hotel:blog' %}">Blog</a>
{#                            <ul class="children">#}
{#                                <li><a href="blog-with-sidebar.html">Blog With Side</a></li>#}
{#                                <li><a href="blog-small.html">Blog Small</a></li>#}
{#                                <li><a href="blog-medium.html">Blog Medium</a></li>#}
{#                                <li><a href="blog-large.html">Blog Large</a></li>#}
{#                                <li><a href="blog-list.html">Blog List</a></li>#}
{#                                <li><a href="blog-detail.html">Blog Detail</a></li>#}
{#                            </ul>#}
                        </li>
                        <li>
                            <a href="#">Gallery</a>
                            <ul class="children">
                                <li><a href="{% url 'hotel:gallery1' %}">Masonry Gallery</a></li>
                                <li><a href="{% url 'hotel:gallery2' %}">Simple Gallery</a></li>
                            </ul>
                        </li>
                        <li class="last">
                            <a href="#">Pages</a>
{#                            <ul class="children">#}
{#                                <li><a href="404.html">404</a></li>#}
{#                                <li><a href="staff.html">Staff</a></li>#}
{#                                <li><a href="login.html">Login</a></li>#}
{#                                <li><a href="signup.html">Signup</a></li>#}
{#                                <li><a href="comingsoon.html">Comingsoon</a></li>#}
{#                            </ul>#}
                        </li>
                        <li>
                            <a href="{% url 'hotel:contact-us' %}">Contact us</a>
                        </li>
                    </ul>
                </nav>
                <!--DL Menu Start-->
                <div id="mg-responsive-navigation" class="dl-menuwrapper">
                    <button class="dl-trigger">Open Menu</button>
                    <ul class="dl-menu">
                        <li class="menu-item mg-parent-menu">
                            <a href="{% url 'hotel:home' %}">Home</a>
                        </li>
                        <li><a href="{% url 'hotel:about-us' %}">About Us</a></li>
                        <li class="menu-item mg-parent-menu"><a href="#">Rooms</a>
                            <ul class="dl-submenu">
                                <li><a href="{% url 'hotel:room' %}">Our Rooms</a></li>
                                <li><a href="{% url 'hotel:room-list' %}">Room List</a></li>
                                <li><a href="{% url 'hotel:room-detail' %}">Room Detail</a></li>
                            </ul>
                        </li>
                        <li class="menu-item mg-parent-menu"><a href="#">Blog</a>
{#                            <ul class="dl-submenu">#}
{#                                <li><a href="blog-with-sidebar.html">Blog With Side</a></li>#}
{#                                <li><a href="blog-small.html">Blog Small</a></li>#}
{#                                <li><a href="blog-medium.html">Blog Medium</a></li>#}
{#                                <li><a href="blog-large.html">Blog Large</a></li>#}
{#                                <li><a href="blog-list.html">Blog List</a></li>#}
{#                                <li><a href="blog-detail.html">Blog Detail</a></li>#}
{#                            </ul>#}
                        </li>
                        <li class="menu-item mg-parent-menu"><a href="#">Event</a>
{#                            <ul class="dl-submenu">#}
{#                                <li><a href="event-small.html">Event Small</a></li>#}
{#                                <li><a href="event-medium.html">Event Medium</a></li>#}
{#                                <li><a href="event-large.html">Event Large</a></li>#}
{#                                <li><a href="event-list.html">Event List</a></li>#}
{#                                <li><a href="event-detail.html">Event Detail</a></li>#}
{#                            </ul>#}
                        </li>
                        <li class="menu-item mg-parent-menu"><a href="#">Gallery</a>
                            <ul class="dl-submenu">
                                <li><a href="{% url 'hotel:gallery1' %}">Masonry Gallery</a></li>
                                <li><a href="{% url 'hotel:gallery2' %}">Simple Gallery</a></li>
                            </ul>
                        </li>
                        <li class="menu-item mg-parent-menu"><a href="#">Pages</a>
{#                            <ul class="dl-submenu">#}
{#                                <li><a href="404.html">404</a></li>#}
{#                                <li><a href="staff.html">Staff</a></li>#}
{#                                <li><a href="login.html">Login</a></li>#}
{#                                <li><a href="signup.html">Signup</a></li>#}
{#                                <li><a href="comingsoon.html">Comingsoon</a></li>#}
{#                            </ul>#}
                        </li>
                        <li class="menu-item mg-parent-menu"><a href="{% url 'hotel:contact-us' %}">Contact us</a></li>
                    </ul>
                </div>
                <!--DL Menu END-->
            </div>
        </div>
    </div>
    <!-- Top Bar Start -->
</header>

templates/frontend/layouts/newsletter.html
<section class="news-letter">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h4 class="title">news letter</h4>
            </div>
            <div class="col-md-6 col-sm-6">
                <!--Input Field Start-->
                <div class="input-field">
                    <div id="mc_embed_signup" class="nl-form-container clearfix">
                        <form action="https://twitter.us16.list-manage.com/subscribe/post-json?u=c768d55d7a9fca1c581bc5614&amp;id=6db56c6523&amp;c=?"
                              method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
                              class="newsletterform validate" target="_blank" novalidate>
                            <input type="email" value="" name="EMAIL" class="email nl-email-input" id="mce-EMAIL"
                                   placeholder="Email address" required>
                            <div style="position: absolute; left: -5000px;">
                                <input type="text" name="b_ba37086d08bdc9f56f3592af0_e38247f7cc" tabindex="-1" value="">
                            </div>
                            <label class="search_icon"><input id="mc-embedded-subscribe" type="submit" name="subscribe"
                                                              value=""></label>
                        </form>
                        <div id="notification_container"></div>
                    </div>
                </div>
                <!--Input Field End-->
            </div>
        </div>
    </div>
</section>

templates/frontend/layouts/script.html
{% load static %}


<!-- Plugin jQuery Library -->
<script src="{% static 'frontend/js/jquery.js' %}"></script>
<!-- Bootstrap jQuery Lifrontend/brary -->
<script src="{% static 'frontend/js/bootstrap.js' %}"></script>
<!-- Parallax jQuery Libfrontend/rary -->
<script src="{% static 'frontend/js/parallax.js' %}"></script>
<!-- Image Loader jQueryfrontend/ Library -->
<script src="{% static 'frontend/js/imageloader.js' %}"></script>
<!-- Browser Detect jQuefrontend/ry Library -->
<script src="{% static 'frontend/js/browser-detect.js' %}"></script>
<!-- Magnafic-popup jQuefrontend/ry Library -->
<script src="{% static 'frontend/js/magnafic-popup.js' %}"></script>
<!-- Twitter jQuery Librfrontend/ary -->
<script src="{% static 'frontend/js/twitter.js' %}"></script>
<!-- Twitter jQuery Librfrontend/ary -->
<script src="{% static 'frontend/js/flickr.js' %}"></script>
<!-- Responsive Menu jQufrontend/ery Library -->
<script src="{% static 'frontend/js/responsive-menu.js' %}"></script>
<!-- Slick Slider jQueryfrontend/ Library -->
<script src="{% static 'frontend/js/slick.js' %}"></script>
<!-- 3D Effect jQuery Lifrontend/brary -->
<script src="{% static 'frontend/js/3deffect.js' %}"></script>
<!-- Isotope jQuery Librfrontend/ary -->
<script src="{% static 'frontend/js/isotope.js' %}"></script>
<!-- Date Picker jQuery frontend/Library -->
<script src="{% static 'frontend/js/datepicker.js' %}"></script>
<!-- Custom jQuery Librafrontend/ry -->
<script src="{% static 'frontend/js/custom.js' %}"></script>

templates/frontend/layouts/switcher.html
<div class="switcher-wrapper">
		<div class="switcher-btn"> <i class='bx bx-cog bx-spin'></i>
		</div>
		<div class="switcher-body">
			<h5 class="mb-0 text-uppercase">Theme Customizer</h5>
			<hr/>
			<h6 class="mb-0">Theme Styles</h6>
			<hr/>
			<div class="d-flex align-items-center justify-content-between">
				<div class="custom-control custom-radio">
					<input type="radio" id="darkmode" name="customRadio" class="custom-control-input">
					<label class="custom-control-label" for="darkmode">Dark Mode</label>
				</div>
				<div class="custom-control custom-radio">
					<input type="radio" id="lightmode" name="customRadio" checked class="custom-control-input">
					<label class="custom-control-label" for="lightmode">Light Mode</label>
				</div>
			</div>
			<hr/>
			<div class="custom-control custom-switch">
				<input type="checkbox" class="custom-control-input" id="DarkSidebar">
				<label class="custom-control-label" for="DarkSidebar">Dark Sidebar</label>
			</div>
			<hr/>
			<div class="custom-control custom-switch">
				<input type="checkbox" class="custom-control-input" id="ColorLessIcons">
				<label class="custom-control-label" for="ColorLessIcons">Color Less Icons</label>
			</div>
		</div>
	</div>